### PR TITLE
Fixed the buttons on the daily log page

### PR DESCRIPTION
**Pull request by fatIvan**
Fixed the buttons on the daily log page, as well as the order each input comes out. For now, when the user selects an entry type, that type will be highlighted and the cancel button shows up. Unless the user clicks the cancel button, the user cannot change the entry type. I also uncommented a part of the code in the beginning to add and test the functionality of the cancel button. The cancel button should work as expected, the functionality of the save buttons isn't implemented though.

### CODE REVIEW

**Comment by fatIvan** [comment]
I am not sure how this happened. I didn't even touch collectionitems.js file.

**Comment by NoahT** [comment]
@fatIvan please make sure your branch is in sync this time. We had a lot of trouble with resolving conflicts on your branch when approving your PR a week ago so it is important that you do this change whenever possible.

**Review by NoahT — CHANGES_REQUESTED** [review]
Please resolve the merge conflicts on your branch before we review these changes.

**Comment by fatIvan** [comment]
Sorry I am so confused right now. I literally pulled from main before working on my new branch, how are there still conflicts? The only two files I modified are dailylog.js and dailylog.html. I didn't even touch the rest.

**Comment by fatIvan** [comment]
Now the time no longer shows up.

**Comment by yuzilyu** [comment]
I am going to close this pr for now since the branch had much changes since.

**Pull request closed without merging**
