### PR TITLE
Add photo to team.md

### PR DESCRIPTION
**Pull request by thanhtong010**

### CODE REVIEW

**Comment by thanhtong010** [comment]
It seems like the PR is having issues w/ daily_test.js, not sure if I should just delete this file for now

**Comment by NoahT** [comment]
Delete it for now. The issue is that `daily.test.js` is using Puppeteer (an import not included in the `package.json` on your branch)

**Review by NoahT — CHANGES_REQUESTED** [review]
See comment

**Comment by thanhtong010** [comment]
Ok got it

**Pull request merged**
