### PR TITLE
Repo clean up

### PR DESCRIPTION
**Pull request by yuzilyu**
`source/image` directory is now merged with `source/images`
Deleted `source/less`
Deleted `source/mock_data`
Delete `source/video`
Renamed branding material images

### CODE REVIEW

**Comment by yuzilyu** [comment]
npm install error ss
I tried `npm install` on my local machine and got this error. However, I cannot find `event-emitter` under `node-modules`

**Comment by yuzilyu** [comment]
Issue fixed

**Review by NoahT — CHANGES_REQUESTED** [review]
We cannot remove the `package-lock.json`. Please delete the existing `package-lock.json`, re-run `npm i` and commit the new lock file

**Comment by yuzilyu** [comment]
@NoahT Idt I deleted package-lock? I did re-run `npm install` to get rid of the issue. The issue was I had package.json opened in an editor

**Comment by yuzilyu** [comment]
> We cannot remove the `package-lock.json`. Please delete the existing `package-lock.json`, re-run `npm i` and commit the new lock file

I just deleted package-lock and re-ran `npm install`

**Review by NoahT — APPROVED** [review]
LGTM

**Pull request merged**
